// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwmvqWuB3-2U1TNUIFE4Jqs55tCDH7V_o',
    appId: '1:423845426192:web:b632da2d7d9e091bd08695',
    messagingSenderId: '423845426192',
    projectId: 'updatefooddelivery',
    authDomain: 'updatefooddelivery.firebaseapp.com',
    storageBucket: 'updatefooddelivery.appspot.com',
    measurementId: 'G-Z8S9KLZKMM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOo-bt1-hYXqjobo_15p6fSSo6vBYTC5s',
    appId: '1:423845426192:android:61ceb5623d057dafd08695',
    messagingSenderId: '423845426192',
    projectId: 'updatefooddelivery',
    storageBucket: 'updatefooddelivery.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd1-HdPnYo5I6ErSBUraV2Cll5BV-Gb-o',
    appId: '1:423845426192:ios:dc36d7f6cb276748d08695',
    messagingSenderId: '423845426192',
    projectId: 'updatefooddelivery',
    storageBucket: 'updatefooddelivery.appspot.com',
    iosBundleId: 'com.example.shivamFoodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd1-HdPnYo5I6ErSBUraV2Cll5BV-Gb-o',
    appId: '1:423845426192:ios:5208a2d6f3103300d08695',
    messagingSenderId: '423845426192',
    projectId: 'updatefooddelivery',
    storageBucket: 'updatefooddelivery.appspot.com',
    iosBundleId: 'com.example.shivamFoodDeliveryApp.RunnerTests',
  );
}
